config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "rooms#rooms"

  resources :room_messages
  resources :rooms

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :room_messages, dependent: :destroy, inverse_of: :room
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room, inverse_of: :room_messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
    before_action :load_entities

    def create
        @room_message = RoomMessage.create room: @room, 
                        message: params.dig(:room_message, :message)

        RoomChannel.broadcast_to @room, @room_message
    end

    private
        def load_entities
            @room = Room.find(params.dig(:room_message, :room_id))
        end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
    before_action :load_entities

    def rooms
    end

    def index
        @rooms = Room.all
    end

    def show
        @room_message = RoomMessage.new(room: @room)
        @room_messages = @room.room_messages
    end

    def new
        @room = Room.new
    end

    def create
        @room = Room.new(permitted_parameters)

        if @room.save
          flash[:success] = "Room #{@room.name} was created successfully"
          redirect_to rooms_path
        else
          render :new
        end
    end

    def edit
    end

    def update
        if @room.update_attributes(permitted_parameters)
          flash[:success] = "Room #{@room.name} was updated successfully"
          redirect_to rooms_path
        else
          render :new
        end
    end

    def destroy
        @room = Room.find(params[:id])
        @room.destroy

        redirect_to rooms_path
    end

    private
        def load_entities
            @rooms = Room.all
            @room = Room.find(params[:id]) if params[:id]
        end

        def permitted_parameters
            params.require(:room).permit(:name)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chat App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400;700;900&family=Ubuntu&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'room' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= flash[:success] %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-bg">
  <div class="container">
    <%= link_to "Chat App", root_path, class: "navbar-brand mb-0 h1" %>
  </div>
</nav>

app/views/partials/_rooms.html.erb
<div class="card-body">
  <ul class="list-group list-group-flush">
    <% if @rooms.present? %>
      <% @rooms.each do |room| %>
        <div class="row list-group-item">
          <%= link_to room.name, room_path(room.id), class: "col-sm-10 room-item" %>
          <%= link_to room_path(room.id),
              method: :delete,
              data: { confirm: "Are you sure you want to delete this room?" },
              class: "col-sm-2 room-item text-right" do
          %>
            <% fa_icon "trash" %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <li class="list-group-item">There are no rooms</li>
    <% end %>
  </ul>
</div>

app/views/rooms/index.html.erb
<%= render "partials/navbar" %>

<br>

<div class="container">
  <% if flash[:success] %>
    <% render "partials/alert" %>
  <% end %>

  <div class="card">
    <h3 class="card-header card-new">
      Rooms
    </h3>
    <%= render "partials/rooms" %>
    <div class="card-footer">
      Want to create a room?
      <%= link_to "Create Room", new_room_path, class: "btn btn-outline-success" %>
    </div>
  </div>

</div>

app/views/rooms/new.html.erb
<%= render "partials/navbar" %>

<br>

<div class="container">
  <div class="card">
    <h3 class="card-header card-new">
        Create Your Room
    </h3>
    <div class="card-body">
        <%= form_with model: @room do |form| %>

            <div class="mb-3">
                <strong><%= form.label :name, class: "form-label " %></strong>
                <%= form.text_field :name, class: "form-control" %>
            </div>

            <%= form.submit class: "btn btn-success"%>
        <% end %>
    </div>
  </div>

</div>

app/views/rooms/rooms.html.erb
<section class="colored-section" id="title">
  <div class="container-fluid-make">
    <div class="row">

      <div class="col-lg-12">
        <h1 class="big-heading">Chat App</h1>
        <p>Let's Chat! Talk to anybody in any room!</p>
        <div class="d-grid gap-2 col-3 mx-auto room-button">
          <%= link_to "Create Room", new_room_path, class: "btn btn-outline-light btn-lg" %>
          <%= link_to "Join Room", rooms_path, class: "btn btn-dark btn-lg" %>
        </div>
      </div>

    </div>
  </div>
</section>

app/views/rooms/show.html.erb
<%= render "partials/navbar" %>

<br>

<div class="container">
  <div class="row">

    <div class="col-lg-3">
      <div class="card">
        <h3 class="card-header card-new">
          <%= link_to "Rooms", rooms_path, class: "rooms-header" %>
        </h3>
        <%= render "partials/rooms" %>
        <div class="card-footer">
          Want to create a room?
          <%= link_to "Create Room", new_room_path, class: "btn btn-outline-success" %>
        </div>
      </div>
    </div>


    <div class="col-lg-9">
      <div class="card">
        <h2 class="card-header">
          <%= @room.name %>
        </h2>
        <div class="card-body">
          <div class="chat" data-channel-subscribe="room" data-room-id="<%= @room.id %>">
            <% @room_messages.each do |room_message| %>

              <% if room_message.message %>
                <div class="chat-message-container">
                  <div class="row no-gutters">

                    <div class="col">
                      <div class="message-content">
                        <p class="text-bubble"><%= room_message.message %></p>
                        <div class="text-right">
                          <small><%= room_message.created_at %></small>
                        </div>
                      </div>
                    </div>

                  </div>
                </div>
              <% end %>

            <% end %>
          </div>

          <div>
            <%= simple_form_for @room_message, remote: true do |form| %>
              <div class="input-group">
                <%= form.input :message,
                    as: :string,
                    wrapper: false,
                    label: false,
                    input_html: {
                      autocomplete: "off",
                      placeholder: "Type here ... ",
                      class: "chat-input"
                    }
                %>
                <div class="input-group-append">
                  <%= form.submit "Send", class: 'btn btn-send chat-input'  %>
                </div>
              </div>

              <%= form.input :room_id, as: :hidden %>
            <% end %>
          </div>

        </div>
      </div>
    </div>

  </div>
</div>


<div class="d-none" data-role="message-template">
  <div class="chat-message-container">
    <div class="row no-gutters">

      <div class="col">
        <div class="message-content">
          <p class="text-bubble" data-role="message-text"></p>
          <div class="text-right">
            <small data-role="message-date"></small>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>